# Generated by Django 6.1 on 2026-09-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the doctor.', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly slug. Auto-generated from name if left blank.', max_length=255, unique=True)),
                ('profile_image', models.ImageField(blank=True, help_text='Doctor profile portrait image.', null=True, upload_to='doctors/')),
                ('specialty', models.CharField(blank=True, help_text='Medical specialty (e.g., Reproductive Endocrinologist).', max_length=255, null=True)),
                ('short_bio', models.TextField(blank=True, help_text='Short clinical biography or credential summary.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this doctor profile is published and visible on the public page.')),
                ('display_order', models.IntegerField(default=0, help_text='Sort order index (lower numbers appear first).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
