# Generated by Django 6.1 on 2026-09-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address (e.g., doctor@biopulse.example.com).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(blank=True, help_text='Clinical practice location (e.g., Lahore, Punjab, Pakistan).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number (e.g., +92 300 0000001).', max_length=50, null=True),
        ),
    ]
