# Generated by BioPulse AI Migration
from django.db import migrations
from django.utils.text import slugify

FICTIONAL_DOCTORS = [
    {
        "name": "Dr. Sarah Ahmed",
        "slug": "dr-sarah-ahmed",
        "specialty": "Endocrinologist",
        "short_bio": "Specializes in hormonal disorders, metabolic health, thyroid conditions, and patient-centered endocrine care.",
        "phone": "+92 300 0000001",
        "email": "sarah.ahmed@biopulse.example.com",
        "location": "Lahore, Punjab, Pakistan",
        "display_order": 1,
        "is_active": True,
    },
    {
        "name": "Dr. Ayesha Malik",
        "slug": "dr-ayesha-malik",
        "specialty": "Internal Medicine Specialist",
        "short_bio": "Provides comprehensive adult healthcare with a focus on preventive medicine, chronic conditions, and long-term wellness.",
        "phone": "+92 300 0000002",
        "email": "ayesha.malik@biopulse.example.com",
        "location": "Lahore, Punjab, Pakistan",
        "display_order": 2,
        "is_active": True,
    },
    {
        "name": "Dr. Imran Siddiqui",
        "slug": "dr-imran-siddiqui",
        "specialty": "Endocrinologist",
        "short_bio": "Focuses on diabetes, thyroid disorders, metabolic health, and hormonal conditions with personalized patient guidance.",
        "phone": "+92 300 0000003",
        "email": "imran.siddiqui@biopulse.example.com",
        "location": "Islamabad, Pakistan",
        "display_order": 3,
        "is_active": True,
    },
    {
        "name": "Dr. Fatima Noor",
        "slug": "dr-fatima-noor",
        "specialty": "General Physician",
        "short_bio": "Provides holistic primary healthcare for individuals and families with an emphasis on preventive care and healthy living.",
        "phone": "+92 300 0000004",
        "email": "fatima.noor@biopulse.example.com",
        "location": "Lahore, Punjab, Pakistan",
        "display_order": 4,
        "is_active": True,
    },
    {
        "name": "Dr. Usman Raza",
        "slug": "dr-usman-raza",
        "specialty": "Andrologist",
        "short_bio": "Focuses on men's hormonal health, endocrine assessment, and evidence-based approaches to male health monitoring.",
        "phone": "+92 300 0000005",
        "email": "usman.raza@biopulse.example.com",
        "location": "Rawalpindi, Punjab, Pakistan",
        "display_order": 5,
        "is_active": True,
    },
    {
        "name": "Dr. Hina Tariq",
        "slug": "dr-hina-tariq",
        "specialty": "Women's Health Specialist",
        "short_bio": "Supports women's hormonal and metabolic health through preventive care, education, and personalized health guidance.",
        "phone": "+92 300 0000006",
        "email": "hina.tariq@biopulse.example.com",
        "location": "Karachi, Sindh, Pakistan",
        "display_order": 6,
        "is_active": True,
    },
    {
        "name": "Dr. Hamza Farooq",
        "slug": "dr-hamza-farooq",
        "specialty": "Family Medicine Specialist",
        "short_bio": "Provides family-focused healthcare with an emphasis on preventive health, lifestyle management, and chronic disease support.",
        "phone": "+92 300 0000007",
        "email": "hamza.farooq@biopulse.example.com",
        "location": "Faisalabad, Punjab, Pakistan",
        "display_order": 7,
        "is_active": True,
    },
]


def seed_doctors(apps, schema_editor):
    Doctor = apps.get_model("health", "Doctor")
    
    # Remove or deactivate old temporary placeholder records not in the 7 fictional doctors list
    fictional_slugs = [doc["slug"] for doc in FICTIONAL_DOCTORS]
    Doctor.objects.exclude(slug__in=fictional_slugs).delete()

    for doc_data in FICTIONAL_DOCTORS:
        Doctor.objects.update_or_create(
            slug=doc_data["slug"],
            defaults={
                "name": doc_data["name"],
                "specialty": doc_data["specialty"],
                "short_bio": doc_data["short_bio"],
                "phone": doc_data["phone"],
                "email": doc_data["email"],
                "location": doc_data["location"],
                "display_order": doc_data["display_order"],
                "is_active": doc_data["is_active"],
            },
        )


def reverse_seed(apps, schema_editor):
    Doctor = apps.get_model("health", "Doctor")
    fictional_slugs = [doc["slug"] for doc in FICTIONAL_DOCTORS]
    Doctor.objects.filter(slug__in=fictional_slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_doctor_email_doctor_location_doctor_phone"),
    ]

    operations = [
        migrations.RunPython(seed_doctors, reverse_code=reverse_seed),
    ]
