# Generated by Django 6.1 on 2026-09-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_seed_fictional_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.IntegerField(blank=True, default=0, help_text='Years of clinical practice experience.', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.CharField(blank=True, help_text='Consultation fee or fee range (e.g., Rs. 1,500 - 2,500).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='External profile image URL (e.g., from verified CloudFront CDN).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualifications',
            field=models.CharField(blank=True, help_text='Academic & clinical qualifications (e.g., MBBS, FCPS).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=4.8, help_text='Patient satisfaction rating (e.g., 4.9).', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='reviews_count',
            field=models.IntegerField(blank=True, default=0, help_text='Total verified patient reviews count.', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services_offered',
            field=models.TextField(blank=True, help_text='Key services and conditions treated (e.g., PCOS Management, Infertility, Antenatal Care).', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='wait_time',
            field=models.CharField(blank=True, default='Under 15 Min', help_text='Average clinic wait time.', max_length=50, null=True),
        ),
    ]
