# Generated by BioPulse AI Migration - Onboard Oladoc Gynecologists
import os
import urllib.request
from django.conf import settings
from django.db import migrations

OLADOC_GYNECOLOGISTS = [
    {
        "name": "Dr. Saddiqa Akhtar",
        "slug": "dr-saddiqa-akhtar",
        "specialty": "Gynecologist & Obstetrician (PCOS & Hormonal Specialist)",
        "qualifications": "MBBS, FCPS (Gynecology and Obstetrics)",
        "fee": "Rs. 1,500 (PKR 800 - 1,500)",
        "experience_years": 12,
        "rating": 4.7,
        "reviews_count": 1210,
        "wait_time": "Under 15 Min",
        "location": "Lahore & Gujranwala / Video Consultation",
        "phone": "+92 42 38900939",
        "email": "dr.saddiqa.akhtar@biopulse.health",
        "short_bio": "Dr. Saddiqa Akhtar is a verified Gynecologist and Obstetrician with 12 years of experience. She specializes in Polycystic Ovary Syndrome (PCOS) menstrual regulation, hormonal imbalance therapy, adolescent gynecology, and comprehensive antenatal care.",
        "services_offered": "PCOS Management, Hormonal Cycle Assessment, Antenatal Care, Caesarean (C-Section), Clinical Breast Examination (CBE), Contraceptive Advice",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1774431110-whatsapp-image-2026-03-25-at-14349-pm.webp?t=1774431115",
        "display_order": 1,
        "is_active": True,
    },
    {
        "name": "Dr. Qudsia Nawaz",
        "slug": "dr-qudsia-nawaz",
        "specialty": "Gynecologist, Aesthetic Physician & Obstetrician (Endocrine & PCOS Care)",
        "qualifications": "MBBS, FCPS, MBA, CLIN ED CERT (UK), Fellowship AAA, AARM, BCRM",
        "fee": "Rs. 4,000 - 5,000",
        "experience_years": 22,
        "rating": 5.0,
        "reviews_count": 145,
        "wait_time": "Under 15 Min",
        "location": "Jail Road, Lahore",
        "phone": "+92 42 38900939",
        "email": "dr.qudsia.nawaz@biopulse.health",
        "short_bio": "With over 22 years of clinical excellence and international fellowships, Dr. Qudsia Nawaz specializes in advanced reproductive endocrinology, PCOS metabolic management, hormonal acne, hirsutism treatment, and aesthetic gynecology.",
        "services_offered": "PCOS Metabolic Therapy, Hormonal Acne & Hirsutism Treatment, Endocrine Balancing, Contraception Care, Laparoscopic BTL",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1776249078-whatsapp-image-2026-04-15-at-31939-pm.webp?t=1776249082",
        "display_order": 2,
        "is_active": True,
    },
    {
        "name": "Prof. Dr. Sara Ejaz",
        "slug": "prof-dr-sara-ejaz",
        "specialty": "Senior Professor of Gynecology & Obstetrics (Reproductive Endocrinology)",
        "qualifications": "MBBS, FCPS (Gynecology & Obstetrics)",
        "fee": "Rs. 2,500",
        "experience_years": 30,
        "rating": 4.9,
        "reviews_count": 845,
        "wait_time": "Under 15 Min",
        "location": "24 Block A, Phase 1 Johar Town, Lahore",
        "phone": "+92 42 38900939",
        "email": "prof.sara.ejaz@biopulse.health",
        "short_bio": "Distinguished Professor with 30 years of clinical and academic mastery. Recognized authority in polycystic ovarian syndrome (PCOS), ovarian health restoration, reproductive endocrinology, and high-risk pregnancy management.",
        "services_offered": "PCOS Evaluation & Management, Ovarian Health Monitoring, Hormonal Cycle Assessment, Antenatal Care, Caesarean (C-Section), Contraceptive Advice",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1759403348-1560240670sara-ijaz.webp?t=1759403350",
        "display_order": 3,
        "is_active": True,
    },
    {
        "name": "Dr. Sadia Zulfiqar Cheema",
        "slug": "dr-sadia-zulfiqar-cheema",
        "specialty": "Consultant Gynecologist & Obstetrician (UK Royal College Fellow)",
        "qualifications": "M.B.B.S., F.C.P.S., M.R.C.O.G. (UK), F.R.C.O.G. (UK)",
        "fee": "Rs. 3,000",
        "experience_years": 20,
        "rating": 4.8,
        "reviews_count": 520,
        "wait_time": "15 - 30 Min",
        "location": "Faisal Town & NESPAK Society, Lahore",
        "phone": "+92 42 38900939",
        "email": "dr.sadia.cheema@biopulse.health",
        "short_bio": "UK Royal College Fellow (FRCOG) with 20 years of practice. Highly sought-after for evidence-based management of ovulatory dysfunction, PCOS insulin resistance, fertility guidance, and comprehensive maternal-fetal care.",
        "services_offered": "PCOS Management, Ovulation Induction, Fertility Consultation, Antenatal Checkup, Clinical Breast Examination, Contraceptive Advice",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1639830770_dr-sadiazulifqar-removebg-preview-min.webp?t=1639830785",
        "display_order": 4,
        "is_active": True,
    },
    {
        "name": "Assoc. Prof. Dr. Maria Imran",
        "slug": "assoc-prof-dr-maria-imran",
        "specialty": "Associate Professor of Gynecology & Obstetrician",
        "qualifications": "M.B.B.S., F.C.P.S. (Gynae & Obs.)",
        "fee": "Rs. 3,000 - 4,000",
        "experience_years": 18,
        "rating": 4.8,
        "reviews_count": 610,
        "wait_time": "15 - 30 Min",
        "location": "DHA, Lahore & Video Consultation",
        "phone": "+92 42 38900939",
        "email": "dr.maria.imran@biopulse.health",
        "short_bio": "Associate Professor with 18 years of specialized expertise in PCOS metabolic phenotyping, hormonal health, advanced gynecological procedures, and holistic fertility care.",
        "services_offered": "PCOS & Metabolic Health Guidance, Gynaecological Surgeries, Antenatal Checkup, Contraceptive Advice, Hysterectomy",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1555588866_maria-imran.webp?t=1605631560",
        "display_order": 5,
        "is_active": True,
    },
    {
        "name": "Dr. Tahira Fahad",
        "slug": "dr-tahira-fahad",
        "specialty": "Gynecologist, Laparoscopic Surgeon & Obstetrician",
        "qualifications": "M.B.B.S., F.C.P.S.",
        "fee": "Rs. 1,000 - 2,500",
        "experience_years": 9,
        "rating": 4.9,
        "reviews_count": 430,
        "wait_time": "Under 15 Min",
        "location": "Model Town, Faisal Town & Walton Road, Lahore",
        "phone": "+92 42 38900939",
        "email": "dr.tahira.fahad@biopulse.health",
        "short_bio": "Dr. Tahira Fahad is a recognized laparoscopic surgeon and gynecologist focusing on PCOS diagnosis, ovarian follicular assessment, menstrual irregularity, and minimally invasive treatments.",
        "services_offered": "PCOS Evaluation & Care, Laparoscopic Surgeries, Antenatal Care, Caesarean (C-Section), Breast Examination (CBE)",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1761116640-16201107304f85c858-58a2-40b5-96ab-65b4e5319a12.webp?t=1761116641",
        "display_order": 6,
        "is_active": True,
    },
    {
        "name": "Dr. Hira Noor Hamid",
        "slug": "dr-hira-noor-hamid",
        "specialty": "Gynecologist & Fertility Consultant (PCOS Specialist)",
        "qualifications": "MBBS, MS (Obstetrics & Gynecology)",
        "fee": "Rs. 2,500 - 3,000",
        "experience_years": 9,
        "rating": 4.9,
        "reviews_count": 380,
        "wait_time": "Under 15 Min",
        "location": "Allama Iqbal Town & Canal Garden, Lahore",
        "phone": "+92 42 38900939",
        "email": "dr.hira.hamid@biopulse.health",
        "short_bio": "Reproductive health specialist dedicated to PCOS subfertility management, ovulation tracking, hormonal balancing, and personalized fertility journey guidance with compassionate patient support.",
        "services_offered": "PCOS Protocol Care, Ovulation Assessment, Early Pregnancy Assessment, Antenatal Care, Family Planning",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1789630010-whatsapp-image-2026-09-17-at-122205-pm.webp?t=1789630013",
        "display_order": 7,
        "is_active": True,
    },
    {
        "name": "Dr. Tanzeela Rehman",
        "slug": "dr-tanzeela-rehman",
        "specialty": "Gynecologist & Aesthetic Gynecologist (PCOS & Lifestyle)",
        "qualifications": "CMT, MBBS, FCPS (Obs & Gynae)",
        "fee": "Rs. 1,000 - 3,500",
        "experience_years": 15,
        "rating": 4.8,
        "reviews_count": 750,
        "wait_time": "15 - 30 Min",
        "location": "Johar Town & Canal Road, Lahore",
        "phone": "+92 42 38900939",
        "email": "dr.tanzeela.rehman@biopulse.health",
        "short_bio": "Dr. Tanzeela Rehman combines 15 years of clinical mastery with lifestyle and metabolic therapies for women with PCOS, chronic anovulation, and aesthetic pelvic wellness.",
        "services_offered": "PCOS Lifestyle Support, High-Risk Antenatal Care, C-Section, Aesthetic Gynecology, Contraception",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1762883681-whatsappimage2025-11-11at105210pm-removebg-preview.webp?t=1762883683",
        "display_order": 8,
        "is_active": True,
    },
    {
        "name": "Dr. Shazia Zulfiqar",
        "slug": "dr-shazia-zulfiqar",
        "specialty": "Consultant Gynecologist & Obstetrician",
        "qualifications": "M.B.B.S., F.C.P.S. (Gynecology & Obstetrics)",
        "fee": "Rs. 1,500 - 2,500",
        "experience_years": 13,
        "rating": 4.8,
        "reviews_count": 390,
        "wait_time": "Under 15 Min",
        "location": "Jail Road, Mughalpura & Jallo Mor, Lahore",
        "phone": "+92 42 38900939",
        "email": "dr.shazia.zulfiqar@biopulse.health",
        "short_bio": "Compassionate specialist with 13 years of practice in PCOS symptom mitigation, pelvic pain management, hormonal balance, and comprehensive maternal health.",
        "services_offered": "PCOS Management, Antenatal Care, Caesarean (C-Section), Contraceptive Advice, Clinical Breast Exam",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1686741367_4b9cb73a-4a31-4efa-8644-1cee832ea4f2.webp?t=1695196099",
        "display_order": 9,
        "is_active": True,
    },
    {
        "name": "Dr. Muniba Tahir",
        "slug": "dr-muniba-tahir",
        "specialty": "Gynecologist & Obstetrician (PCOS & Endocrine Health)",
        "qualifications": "MBBS, FCPS (Gynecology and Obstetrics)",
        "fee": "Rs. 2,000 - 4,000",
        "experience_years": 10,
        "rating": 4.8,
        "reviews_count": 490,
        "wait_time": "Under 15 Min",
        "location": "DHA, Jail Road & Johar Town, Lahore",
        "phone": "+92 42 38900939",
        "email": "dr.muniba.tahir@biopulse.health",
        "short_bio": "Experienced in women's hormonal balance and PCOS metabolic screening. Provides evidence-based lifestyle coaching, cycle regulation, and complete maternal care across Lahore clinics.",
        "services_offered": "PCOS Protocol Care, Antenatal Care, Caesarean (C-Section), Hormonal Profiling, Contraceptive Advice",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1767871057-download-3-picsart-backgroundremover.webp?t=1767871058",
        "display_order": 10,
        "is_active": True,
    },
    {
        "name": "Assist Prof. Dr. Shaheen Khan Bahadar Awan",
        "slug": "assist-prof-dr-shaheen-awan",
        "specialty": "Assistant Professor of Gynecology & Infertility / PCOS Consultant",
        "qualifications": "MBBS, FCPS (Gynae & Obs)",
        "fee": "Rs. 2,000 - 2,500",
        "experience_years": 14,
        "rating": 4.9,
        "reviews_count": 310,
        "wait_time": "Under 15 Min",
        "location": "Lahore & Online Video Consultation",
        "phone": "+92 42 38900939",
        "email": "dr.shaheen.awan@biopulse.health",
        "short_bio": "Assistant Professor with 14 years of expertise leading specialized PCOS and infertility clinics. Expert in ovulatory stimulation, ultrasound tracking, and hormonal wellness.",
        "services_offered": "PCOS Clinic, Infertility Workup, Ovulation Induction, Antenatal Care, Gynecological Consultation",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1761116640-16201107304f85c858-58a2-40b5-96ab-65b4e5319a12.webp?t=1761116641",
        "display_order": 11,
        "is_active": True,
    },
]


def download_image(url, filename):
    try:
        doctors_media_dir = os.path.join(settings.MEDIA_ROOT, "doctors")
        os.makedirs(doctors_media_dir, exist_ok=True)
        local_path = os.path.join(doctors_media_dir, filename)
        if not os.path.exists(local_path):
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            with urllib.request.urlopen(req, timeout=10) as resp:
                data = resp.read()
                if len(data) > 500:
                    with open(local_path, "wb") as f:
                        f.write(data)
                    return f"doctors/{filename}"
        else:
            return f"doctors/{filename}"
    except Exception as e:
        print(f"Image download warning for {filename}: {e}")
    return None


def seed_oladoc_gynecologists(apps, schema_editor):
    Doctor = apps.get_model("health", "Doctor")

    # Set existing fictional doctors to display_order after these top specialists or keep them
    Doctor.objects.filter(is_active=True).update(display_order=20)

    for doc_data in OLADOC_GYNECOLOGISTS:
        slug = doc_data["slug"]
        image_url = doc_data.get("profile_image_url")
        filename = f"{slug}.webp"
        local_img = download_image(image_url, filename) if image_url else None

        defaults = {
            "name": doc_data["name"],
            "specialty": doc_data["specialty"],
            "qualifications": doc_data["qualifications"],
            "fee": doc_data["fee"],
            "experience_years": doc_data["experience_years"],
            "rating": doc_data["rating"],
            "reviews_count": doc_data["reviews_count"],
            "wait_time": doc_data["wait_time"],
            "location": doc_data["location"],
            "phone": doc_data["phone"],
            "email": doc_data["email"],
            "short_bio": doc_data["short_bio"],
            "services_offered": doc_data["services_offered"],
            "profile_image_url": image_url,
            "display_order": doc_data["display_order"],
            "is_active": doc_data["is_active"],
        }
        if local_img:
            defaults["profile_image"] = local_img

        Doctor.objects.update_or_create(slug=slug, defaults=defaults)


def reverse_oladoc_seed(apps, schema_editor):
    Doctor = apps.get_model("health", "Doctor")
    oladoc_slugs = [doc["slug"] for doc in OLADOC_GYNECOLOGISTS]
    Doctor.objects.filter(slug__in=oladoc_slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0004_doctor_experience_years_doctor_fee_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_oladoc_gynecologists, reverse_code=reverse_oladoc_seed),
    ]
