# Generated by BioPulse AI Migration - Onboard Oladoc Urologists for Male Hypogonadism
import os
import urllib.request
from django.conf import settings
from django.db import migrations

OLADOC_UROLOGISTS = [
    {
        "name": "Prof. Dr. Fawad Nasrullah",
        "slug": "prof-dr-fawad-nasrullah",
        "specialty": "Senior Professor of Urology, Andrologist & Male Sexual Health Specialist",
        "qualifications": "MBBS, FCPS (Urology), FICS (USA)",
        "fee": "Rs. 5,000",
        "experience_years": 28,
        "rating": 4.8,
        "reviews_count": 380,
        "wait_time": "15 - 30 Min",
        "location": "Shadman & Jail Road, Lahore / Video Consultation",
        "phone": "+92 42 38900939",
        "email": "prof.fawad.nasrullah@biopulse.health",
        "short_bio": "Senior Professor of Urology & Andrology with 28 years of academic and clinical excellence. Recognized authority in male hypogonadism, testosterone deficiency protocols, andrology, and complex male reproductive disorders.",
        "services_offered": "Male Hypogonadism Treatment, Testosterone Monitoring, Andrology Evaluation, Infertility Workup, Endoscopic Procedures",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1560144737_fawad-nasrullah.webp?t=1605619991",
        "display_order": 12,
        "is_active": True,
    },
    {
        "name": "Dr. Usama Nawaz Ghumman",
        "slug": "dr-usama-nawaz-ghumman",
        "specialty": "Consultant Urologist, Andrologist & Reconstructive Surgeon",
        "qualifications": "MBBS (KEMU), FRCS Urology (England), MD (USA), Fellowship Genito-Urethral Reconstruction (England)",
        "fee": "Rs. 3,000 - 3,500",
        "experience_years": 10,
        "rating": 4.9,
        "reviews_count": 240,
        "wait_time": "15 - 30 Min",
        "location": "DHA & Gulberg, Lahore / Video Consultation",
        "phone": "+92 42 38900939",
        "email": "dr.usama.ghumman@biopulse.health",
        "short_bio": "UK & USA fellowship-trained Urologist and Andrologist specializing in male hypogonadism, endocrine deficiency syndromes, andrological wellness, and genito-urethral reconstruction with 10 years of clinical practice.",
        "services_offered": "Male Hypogonadism Management, Andrology Consultation, Testosterone Optimization, Penile & Urethral Reconstruction",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1729167276_Dr_Usama_Nawaz_Ghumman-removebg-preview.webp?t=1729167278",
        "display_order": 13,
        "is_active": True,
    },
    {
        "name": "Assist. Prof. Dr. Ghulam Ghous",
        "slug": "assist-prof-dr-ghulam-ghous",
        "specialty": "Assistant Professor of Urology, Andrologist & Male Health Specialist",
        "qualifications": "M.B.B.S, F.C.P.S (Urology)",
        "fee": "Rs. 2,000 - 2,500",
        "experience_years": 11,
        "rating": 4.8,
        "reviews_count": 310,
        "wait_time": "15 - 30 Min",
        "location": "House #729, Shadman (Opposite Fatima Memorial Hospital), Lahore",
        "phone": "+92 42 38900939",
        "email": "dr.ghulam.ghous@biopulse.health",
        "short_bio": "Assistant Professor of Urology and Andrology with 11 years of experience. Specializes in diagnosing and treating male hypogonadism, testosterone deficit, and male sexual health through evidence-based endocrine management.",
        "services_offered": "Hypogonadism Therapy, Andrology Clinic, Testosterone Assessment, Kidney & Bladder Laser Surgery, Lithotripsy",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1560230550_ghulam-ghous.webp?t=1691056599",
        "display_order": 14,
        "is_active": True,
    },
    {
        "name": "Dr. Hafiz Abdul Momin",
        "slug": "dr-hafiz-abdul-momin",
        "specialty": "Consultant Urologist, Andrologist & Male Sexual Health Specialist",
        "qualifications": "MBBS, FCPS (Urology)",
        "fee": "Rs. 2,000 - 3,000",
        "experience_years": 13,
        "rating": 4.9,
        "reviews_count": 460,
        "wait_time": "Under 15 Min",
        "location": "Johar Town & Jail Road, Lahore / Video Consultation",
        "phone": "+92 42 38900939",
        "email": "dr.hafiz.momin@biopulse.health",
        "short_bio": "Accomplished Urologist and Andrologist with 13 years of practice. Focuses on male hypogonadism, testosterone replenishment, fatigue-related hormonal deficits, erectile dysfunction, and comprehensive andrological care.",
        "services_offered": "Male Hypogonadism Assessment, Testosterone Replacement Protocols, Andrology & Sexology, Endoscopic Laser Surgery",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/dr-hafiz-abdul-momin-urologist-lahore.webp?t=1605648245",
        "display_order": 15,
        "is_active": True,
    },
    {
        "name": "Dr. Shahid Hussain Dreshak",
        "slug": "dr-shahid-hussain-dreshak",
        "specialty": "Consultant Urologist & Andrology Practitioner",
        "qualifications": "MBBS, MS (Urology)",
        "fee": "Rs. 2,000 - 3,000",
        "experience_years": 15,
        "rating": 4.6,
        "reviews_count": 220,
        "wait_time": "15 - 30 Min",
        "location": "Faisal Town & Model Town, Lahore / Video Consultation",
        "phone": "+92 42 38900939",
        "email": "dr.shahid.dreshak@biopulse.health",
        "short_bio": "Consultant Urologist with 15 years of clinical experience specializing in andrological conditions, male hypogonadism screening, male subfertility, and minimally invasive endourology.",
        "services_offered": "Hypogonadism Screening, Male Fertility Evaluation, Andrology Consultation, Renal & Urological Surgery",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1778496759-shahiddrishak50.webp?t=1778496776",
        "display_order": 16,
        "is_active": True,
    },
    {
        "name": "Dr. Muhammad Fayyaz",
        "slug": "dr-muhammad-fayyaz",
        "specialty": "Consultant Urologist, Sexologist & Robotic Surgeon",
        "qualifications": "MBBS, Certified in Robotic & Transplant Surgery, FCPS (Urology) (SIUT)",
        "fee": "Rs. 3,000 - 4,000",
        "experience_years": 10,
        "rating": 4.8,
        "reviews_count": 180,
        "wait_time": "15 - 30 Min",
        "location": "Gulberg & Jail Road, Lahore / Video Consultation",
        "phone": "+92 42 38900939",
        "email": "dr.muhammad.fayyaz@biopulse.health",
        "short_bio": "SIUT-trained Urologist and Sexologist with 10 years of experience. Provides clinical evaluation for male hormonal failure, hypogonadism, sexual dysfunction, and advanced robotic urological procedures.",
        "services_offered": "Male Hypogonadism Assessment, Sexology & Andrology, Robotic Surgery, Urological Reconstruction",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1704435662_MuhammadFayyazpicture.webp?t=1747813233",
        "display_order": 17,
        "is_active": True,
    },
    {
        "name": "Assist Prof. Dr. Shaheen Khan Bahadar Awan (Male Health Clinic)",
        "slug": "assist-prof-dr-shaheen-awan-urology",
        "specialty": "Assistant Professor of Urology & Male Fertility Consultant",
        "qualifications": "MBBS, MS (Urology Gold Medalist)",
        "fee": "Rs. 2,000 - 2,500",
        "experience_years": 14,
        "rating": 4.9,
        "reviews_count": 310,
        "wait_time": "15 - 30 Min",
        "location": "146-A, GOR-V Block A, Faisal Town (In Front Of Jinnah Hospital), Lahore",
        "phone": "+92 42 38900939",
        "email": "dr.shaheen.urology@biopulse.health",
        "short_bio": "Gold Medalist Urologist and Assistant Professor with 14 years of clinical leadership. Leads specialized clinics for male hypogonadism, testicular endocrine disorders, and male factor subfertility.",
        "services_offered": "Male Hypogonadism Evaluation, Fertility Workup, Andrological Surgery, Bladder & Kidney Surgery",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1646378240_shaheen-removebg-preview-min.webp?t=1646378250",
        "display_order": 18,
        "is_active": True,
    },
    {
        "name": "Dr. Muhammad Yahya Hasan",
        "slug": "dr-muhammad-yahya-hasan",
        "specialty": "Consultant Urologist & Men's Health Specialist",
        "qualifications": "MBBS, MS (Urology)",
        "fee": "Rs. 2,500 - 3,500",
        "experience_years": 10,
        "rating": 5.0,
        "reviews_count": 170,
        "wait_time": "Under 15 Min",
        "location": "DHA & Johar Town, Lahore / Video Consultation",
        "phone": "+92 42 38900939",
        "email": "dr.yahya.hasan@biopulse.health",
        "short_bio": "Highly rated Consultant Urologist with 10 years of practice. Expertise in adult male endocrine evaluation, hypogonadism screening, and minimally invasive endourology.",
        "services_offered": "Hypogonadism Consultation, Endoscopic Procedures, Men's Health Screening, Bladder Health",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1742550123_Muhammad_Yahya_Hasan-removebg-preview.webp?t=1742550124",
        "display_order": 19,
        "is_active": True,
    },
    {
        "name": "Dr. Muhammad Hanan Yousaf",
        "slug": "dr-muhammad-hanan-yousaf",
        "specialty": "Consultant Urologist & Clinical Fellow",
        "qualifications": "MBBS, FCPS (Urology), Clinical Fellowship",
        "fee": "Rs. 3,000",
        "experience_years": 7,
        "rating": 4.8,
        "reviews_count": 130,
        "wait_time": "Under 15 Min",
        "location": "Jail Road & Shadman, Lahore / Video Consultation",
        "phone": "+92 42 38900939",
        "email": "dr.hanan.yousaf@biopulse.health",
        "short_bio": "Fellowship-trained Urologist with 7 years of clinical experience providing specialized care for male reproductive and endocrine symptoms, testicular conditions, and reconstructive urology.",
        "services_offered": "Urological Consultation, Male Health Assessment, Endoscopic Surgery, Hydrocele Surgery",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1718166392_fe332c79-dfdd-4274-bc3a-5996bba85f27.webp?t=1728278217",
        "display_order": 20,
        "is_active": True,
    },
    {
        "name": "Dr. Nuzhat Faqir Hussain",
        "slug": "dr-nuzhat-faqir-hussain",
        "specialty": "Consultant Urologist",
        "qualifications": "MBBS, FCPS (Urology), M.R.C.S",
        "fee": "Rs. 3,000",
        "experience_years": 6,
        "rating": 4.5,
        "reviews_count": 120,
        "wait_time": "15 - 30 Min",
        "location": "Allama Iqbal Town & Faisal Town, Lahore / Video Consultation",
        "phone": "+92 42 38900939",
        "email": "dr.nuzhat.hussain@biopulse.health",
        "short_bio": "UK MRCS certified Consultant Urologist with 6 years of hospital practice. Offers consultations for male hormonal symptoms, urinary tract conditions, and endourological interventions.",
        "services_offered": "Urological Consultation, ESWL, Endoscopic Procedures, General Urology, Catheterization",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1783598514-nuzhat-faqir-hussain.webp?t=1783598516",
        "display_order": 21,
        "is_active": True,
    },
]


def download_image(url, filename):
    try:
        doctors_media_dir = os.path.join(settings.MEDIA_ROOT, "doctors")
        os.makedirs(doctors_media_dir, exist_ok=True)
        local_path = os.path.join(doctors_media_dir, filename)
        if not os.path.exists(local_path):
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            with urllib.request.urlopen(req, timeout=10) as resp:
                data = resp.read()
                if len(data) > 500:
                    with open(local_path, "wb") as f:
                        f.write(data)
                    return f"doctors/{filename}"
        else:
            return f"doctors/{filename}"
    except Exception as e:
        print(f"Urologist image download warning for {filename}: {e}")
    return None


def seed_oladoc_urologists(apps, schema_editor):
    Doctor = apps.get_model("health", "Doctor")

    for doc_data in OLADOC_UROLOGISTS:
        slug = doc_data["slug"]
        image_url = doc_data.get("profile_image_url")
        filename = f"{slug}.webp"
        local_img = download_image(image_url, filename) if image_url else None

        defaults = {
            "name": doc_data["name"],
            "specialty": doc_data["specialty"],
            "qualifications": doc_data["qualifications"],
            "fee": doc_data["fee"],
            "experience_years": doc_data["experience_years"],
            "rating": doc_data["rating"],
            "reviews_count": doc_data["reviews_count"],
            "wait_time": doc_data["wait_time"],
            "location": doc_data["location"],
            "phone": doc_data["phone"],
            "email": doc_data["email"],
            "short_bio": doc_data["short_bio"],
            "services_offered": doc_data["services_offered"],
            "profile_image_url": image_url,
            "display_order": doc_data["display_order"],
            "is_active": doc_data["is_active"],
        }
        if local_img:
            defaults["profile_image"] = local_img

        Doctor.objects.update_or_create(slug=slug, defaults=defaults)


def reverse_urologist_seed(apps, schema_editor):
    Doctor = apps.get_model("health", "Doctor")
    urologist_slugs = [doc["slug"] for doc in OLADOC_UROLOGISTS]
    Doctor.objects.filter(slug__in=urologist_slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0005_seed_oladoc_gynecologists"),
    ]

    operations = [
        migrations.RunPython(seed_oladoc_urologists, reverse_code=reverse_urologist_seed),
    ]
