# Generated by BioPulse AI Migration - Onboard Oladoc Sexologists & Reproductive Endocrinologists
import os
import urllib.request
from django.conf import settings
from django.db import migrations

OLADOC_SEXOLOGISTS = [
    {
        "name": "Dr. Mohsin Asif",
        "slug": "dr-mohsin-asif",
        "specialty": "Andrologist, Diabetologist, Endocrinologist & Sexologist",
        "qualifications": "MBBS, FCPS, EBEEDM (European Board Endocrinology), FECSM, Fellowship Reproductive Medicine (UEMS)",
        "fee": "Rs. 3,000",
        "experience_years": 9,
        "rating": 4.9,
        "reviews_count": 280,
        "wait_time": "Under 15 Min",
        "location": "House #729, Shadman (Opposite Fatima Memorial Hospital), Lahore / Video Consultation",
        "phone": "+92 42 38900939",
        "email": "dr.mohsin.asif@biopulse.health",
        "short_bio": "European Board Certified Endocrinologist & Reproductive Medicine Fellow. Unique dual expertise in managing PCOS metabolic insulin resistance, female endocrine dysregulation, as well as male andropause, hypogonadism, and sexual wellness.",
        "services_offered": "PCOS Metabolic Care, Diabetes Mellitus, Andropause & Male Hypogonadism, Reproductive Medicine, Sexual Health Therapy",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1683299008_b58cbac0-0bc1-4b02-bd32-9ac7fe5f35f3.webp?t=1735364802",
        "display_order": 22,
        "is_active": True,
    },
    {
        "name": "Dr. Muhammad Haris Burki",
        "slug": "dr-muhammad-haris-burki",
        "specialty": "Consultant Sexologist, Sexual Health Specialist & Psychiatrist",
        "qualifications": "MBBS, WPA CME Psych, Ph.D (Sexology), FECSM Sexual Medicine (Holland)",
        "fee": "Rs. 2,500 - 3,000",
        "experience_years": 30,
        "rating": 4.8,
        "reviews_count": 340,
        "wait_time": "15 - 30 Min",
        "location": "Lahore / Online Video Consultation",
        "phone": "+92 42 38900939",
        "email": "dr.haris.burki@biopulse.health",
        "short_bio": "Holland-trained Fellow of the European Committee of Sexual Medicine with 30 years of practice. Specializes in female sexual health (PCOS-related dyspareunia, libido changes) and male hypogonadism and psychosexual counseling.",
        "services_offered": "Female & Male Sexual Medicine, PCOS Hormonal Dyspareunia, Male Hypogonadism Support, Psychosexual Therapy, Anxiety & Depression Treatment",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1551272819_haris-burki.webp?t=1605618893",
        "display_order": 23,
        "is_active": True,
    },
    {
        "name": "Dr. Tanzeel Arshad",
        "slug": "dr-tanzeel-arshad",
        "specialty": "Sexologist, Andrologist & Reproductive Fertility Consultant",
        "qualifications": "MBBS, CRSM (Certified Reproductive & Sexual Medicine)",
        "fee": "Rs. 1,500 - 5,000",
        "experience_years": 5,
        "rating": 4.9,
        "reviews_count": 190,
        "wait_time": "Under 15 Min",
        "location": "Lahore / Online Video Consultation",
        "phone": "+92 42 38900939",
        "email": "dr.tanzeel.arshad@biopulse.health",
        "short_bio": "Certified in Reproductive and Sexual Medicine. Evaluates couples for male and female hormonal imbalances, PCOS-related ovulatory issues, male hypogonadism, and comprehensive sexual health.",
        "services_offered": "Male & Female Infertility, Hormonal Health & Endocrinology, PCOS Care Support, Male Sexual Health Management, Erectile Dysfunction",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1781940898-dr-tanzeel-arshad-photoroom.webp?t=1781940903",
        "display_order": 24,
        "is_active": True,
    },
    {
        "name": "Prof. Dr. Irfan Nazir",
        "slug": "prof-dr-irfan-nazir",
        "specialty": "Professor of Urology, Andrologist & Sexologist (FACS USA)",
        "qualifications": "M.B.B.S, F.C.P.S (Urology), F.A.C.S. (USA)",
        "fee": "Rs. 3,000 - 5,000",
        "experience_years": 21,
        "rating": 4.9,
        "reviews_count": 320,
        "wait_time": "15 - 30 Min",
        "location": "Lahore / Online Video Consultation",
        "phone": "+92 42 38900939",
        "email": "prof.irfan.nazir@biopulse.health",
        "short_bio": "Fellow of the American College of Surgeons and Professor with 21 years of experience in andrology, male hypogonadism, endocrine deficiency, and endourological interventions.",
        "services_offered": "Andrology & Endocrine Evaluation, Male Hypogonadism Management, Erectile Dysfunction, Endoscopic Laser Surgery, Reconstructive Urology",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1560250504_irfan-nazir.webp?t=1742370513",
        "display_order": 25,
        "is_active": True,
    },
    {
        "name": "Dr. Khalil Ahmad",
        "slug": "dr-khalil-ahmad",
        "specialty": "Consultant Urologist, Sexologist & Male Fertility Specialist",
        "qualifications": "MBBS, MS (Urology)",
        "fee": "Rs. 1,500 - 3,000",
        "experience_years": 18,
        "rating": 4.8,
        "reviews_count": 210,
        "wait_time": "15 - 30 Min",
        "location": "Lahore / Online Video Consultation",
        "phone": "+92 42 38900939",
        "email": "dr.khalil.ahmad@biopulse.health",
        "short_bio": "Experienced consultant in urology and sexual health with 18 years of clinical care. Specializes in male subfertility, andrological wellness, and hormonal evaluations.",
        "services_offered": "Male Infertility Evaluation, Sexual Medicine, Andrology Consultation, Genitourinary Surgery",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1711011267_DR._KHALIL_AHMAD__Picture-removebg-preview.webp?t=1711011269",
        "display_order": 26,
        "is_active": True,
    },
    {
        "name": "Dr. Ahmad Nadeem",
        "slug": "dr-ahmad-nadeem",
        "specialty": "Consultant Sexologist & Andrologist",
        "qualifications": "M.B.B.S, C.R.S.M, PGD Sexology",
        "fee": "Rs. 2,000 - 3,000",
        "experience_years": 33,
        "rating": 4.7,
        "reviews_count": 250,
        "wait_time": "Under 15 Min",
        "location": "Lahore / Online Video Consultation",
        "phone": "+92 42 38900939",
        "email": "dr.ahmad.nadeem@biopulse.health",
        "short_bio": "Senior clinician with 33 years in sexual medicine and andrology. Focuses on endocrine-related sexual disorders, diabetes-induced dysfunction, and personalized hormonal guidance.",
        "services_offered": "Sexual Medicine Consultation, Andrology Evaluation, Diabetes-Related Sexual Health, Psychosexual Counseling",
        "profile_image_url": "https://d1t78adged64l7.cloudfront.net/images/profile-pics/doctors/1595428153_138650copy-01.webp?t=1679116431",
        "display_order": 27,
        "is_active": True,
    },
]


def download_image(url, filename):
    try:
        doctors_media_dir = os.path.join(settings.MEDIA_ROOT, "doctors")
        os.makedirs(doctors_media_dir, exist_ok=True)
        local_path = os.path.join(doctors_media_dir, filename)
        if not os.path.exists(local_path):
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            with urllib.request.urlopen(req, timeout=10) as resp:
                data = resp.read()
                if len(data) > 500:
                    with open(local_path, "wb") as f:
                        f.write(data)
                    return f"doctors/{filename}"
        else:
            return f"doctors/{filename}"
    except Exception as e:
        print(f"Sexologist image download warning for {filename}: {e}")
    return None


def seed_oladoc_sexologists(apps, schema_editor):
    Doctor = apps.get_model("health", "Doctor")

    for doc_data in OLADOC_SEXOLOGISTS:
        slug = doc_data["slug"]
        image_url = doc_data.get("profile_image_url")
        filename = f"{slug}.webp"
        local_img = download_image(image_url, filename) if image_url else None

        defaults = {
            "name": doc_data["name"],
            "specialty": doc_data["specialty"],
            "qualifications": doc_data["qualifications"],
            "fee": doc_data["fee"],
            "experience_years": doc_data["experience_years"],
            "rating": doc_data["rating"],
            "reviews_count": doc_data["reviews_count"],
            "wait_time": doc_data["wait_time"],
            "location": doc_data["location"],
            "phone": doc_data["phone"],
            "email": doc_data["email"],
            "short_bio": doc_data["short_bio"],
            "services_offered": doc_data["services_offered"],
            "profile_image_url": image_url,
            "display_order": doc_data["display_order"],
            "is_active": doc_data["is_active"],
        }
        if local_img:
            defaults["profile_image"] = local_img

        Doctor.objects.update_or_create(slug=slug, defaults=defaults)


def reverse_sexologist_seed(apps, schema_editor):
    Doctor = apps.get_model("health", "Doctor")
    sexologist_slugs = [doc["slug"] for doc in OLADOC_SEXOLOGISTS]
    Doctor.objects.filter(slug__in=sexologist_slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0006_seed_oladoc_urologists_hypogonadism"),
    ]

    operations = [
        migrations.RunPython(seed_oladoc_sexologists, reverse_code=reverse_sexologist_seed),
    ]
