# Generated by Django 5.2.7 on 2026-09-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_seed_oladoc_sexologists'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pathway',
            field=models.CharField(choices=[('female_pcos', 'Female PCOS'), ('male_hypogonadism', 'Male Hypogonadism'), ('both', 'Both Genders / General Endocrine')], default='female_pcos', help_text='Clinical pathway served by this doctor (female_pcos, male_hypogonadism, both).', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='relevance_reason',
            field=models.CharField(blank=True, help_text="Concise clinical relevance rationale (e.g., 'Specialist for PCOS care', 'Specialist for hormonal evaluation').", max_length=255, null=True),
        ),
    ]
