import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, X, Send, Bot } from 'lucide-react';
import { useUserHealth } from '../../context/UserHealthContext';

interface ChatMessage {
  id: string;
  sender: 'user' | 'ai';
  text: string;
  timestamp: string;
}

const QUICK_PROMPTS = [
  'Explain my PCOS screening result',
  'What factors influenced my risk score?',
  'What should I discuss with my doctor?',
  'Why do I feel bloated today?',
  'What foods support my current phase?',
  'Prepare my doctor consultation summary',
];

export const FloatingOvaSenseAI: React.FC = () => {
  const { userProfile, snapshotMetrics, isAiChatOpen, activeAiPrompt, toggleAiChat, closeAiChat } = useUserHealth();
  const [inputText, setInputText] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const lastProcessedPrompt = useRef<string | undefined>(undefined);

  const initialGreeting = `Hello ${userProfile.fullName ? userProfile.fullName.split(' ')[0] : 'there'}! I'm your OvaSense AI Digital Twin. ${
    snapshotMetrics.cycleDay > 0
      ? `You are currently on Day ${snapshotMetrics.cycleDay} (${snapshotMetrics.phaseName}).`
      : 'I am here to help you understand your cycle, symptoms, and ML health assessments.'
  } How can I assist you today?`;

  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: 'msg_initial',
      sender: 'ai',
      text: initialGreeting,
      timestamp: 'Just now',
    },
  ]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    if (isAiChatOpen) {
      scrollToBottom();
    }
  }, [messages, isAiChatOpen]);

  // Handle incoming active prompt triggers (from "Discuss with AI Twin" or other action buttons)
  useEffect(() => {
    if (activeAiPrompt && isAiChatOpen && activeAiPrompt !== lastProcessedPrompt.current) {
      lastProcessedPrompt.current = activeAiPrompt;
      handleSendMessage(activeAiPrompt);
    }
  }, [activeAiPrompt, isAiChatOpen]);

  const handleSendMessage = (textToSend?: string) => {
    const text = textToSend || inputText;
    if (!text.trim()) return;

    const userMsg: ChatMessage = {
      id: `usr_${Date.now()}`,
      sender: 'user',
      text: text.trim(),
      timestamp: 'Now',
    };

    setMessages((prev) => [...prev, userMsg]);
    if (!textToSend) {
      setInputText('');
    }
    setIsTyping(true);

    // Intelligent context-driven responses
    setTimeout(() => {
      let replyText = `I've analyzed your question against your longitudinal health records and current ${snapshotMetrics.phaseName || 'cycle phase'}. If you have specific questions about symptoms, nutrition, or your screening risk, feel free to ask!`;

      const lower = text.toLowerCase();

      if (lower.includes('pcos') || lower.includes('screening') || lower.includes('risk') || lower.includes('factors') || lower.includes('result') || lower.includes('shap')) {
        replyText = `Your PCOS screening assessment is generated by the OvaSense Extra Trees machine-learning model (trained across 16 clinical, symptom, cycle, and lifestyle features) with exact TreeSHAP factor attribution.

Key points regarding your screening result:
1. Screening Threshold: The model uses a calibrated 38% cutoff for risk stratification.
2. Primary Influencing Factors: Features such as cycle length regularity, metabolic markers (BMI, weight fluctuations), and hyperandrogenism indicators (hirsutism, acne) have the highest Shapley importance.
3. Educational Purpose: This score is a clinical screening aid to empower your healthcare discussions, not a definitive diagnosis.

Would you like me to prepare specific questions to bring to your doctor?`;
      } else if (lower.includes('doctor') || lower.includes('physician') || lower.includes('appointment') || lower.includes('discuss with my doctor')) {
        replyText = `Here are 4 recommended discussion topics for your healthcare provider:
1. Review of your cycle regularity, follicular phase length, and ovulation consistency.
2. Whether confirmatory diagnostic workups are indicated (e.g. pelvic ultrasound for ovarian morphology, fasting insulin/glucose, LH/FSH ratio, free testosterone).
3. Targeted lifestyle modifications (glycemic stabilization, protein-forward breakfast, low-inflammatory meal planning).
4. Review of current supplements or medications (e.g. Inositol, Magnesium, Vitamin D).

Tip: You can click "Export Clinician Summary PDF" on your dashboard to bring a structured printout to your appointment.`;
      } else if (lower.includes('phase') || lower.includes('cycle') || lower.includes('period') || lower.includes('ovulat')) {
        replyText = snapshotMetrics.cycleDay > 0
          ? `You are on Day ${snapshotMetrics.cycleDay} of your ${snapshotMetrics.totalCycleDays}-day cycle, currently in the ${snapshotMetrics.phaseName}. In this phase, estrogen levels modulate energy metabolism, insulin sensitivity, and mood.`
          : `You currently haven't logged your last period. Once you add your first cycle entry in the "Your Cycle" tab, I will provide live day-by-day hormone curve estimates and phase-specific recommendations.`;
      } else if (lower.includes('bloat') || lower.includes('bloated') || lower.includes('cramp') || lower.includes('symptom')) {
        replyText = `Mid-cycle and premenstrual symptoms like bloating and mild pelvic tension are commonly tied to hormonal transitions. Hydrating with electrolyte-rich fluids, herbal infusions (peppermint, ginger), and magnesium-rich nourishment helps ease smooth muscle tension.`;
      } else if (lower.includes('food') || lower.includes('nutrition') || lower.includes('diet') || lower.includes('meal')) {
        replyText = `For hormone balance and steady glycemic control:
• Prioritize fiber-rich complex carbohydrates (brown rice, oats, lentils, whole grains).
• Aim for 20-30g of protein per main meal to stabilize postprandial glucose curves.
• Include healthy fats (chia seeds, flaxseeds, walnuts, olive oil) to support steroid hormone synthesis.
• Incorporate antioxidant-rich leafy greens (spinach, methi, palak) for hepatic estrogen clearance.`;
      } else if (lower.includes('summary') || lower.includes('export') || lower.includes('pdf')) {
        replyText = `I have aggregated your 30-day symptom frequency, your cycle metrics (Day ${snapshotMetrics.cycleDay}), and your latest report findings. You can click "Export Clinician Summary PDF" on your dashboard to download the report immediately.`;
      }

      const aiMsg: ChatMessage = {
        id: `ai_${Date.now()}`,
        sender: 'ai',
        text: replyText,
        timestamp: 'Just now',
      };

      setMessages((prev) => [...prev, aiMsg]);
      setIsTyping(false);
    }, 850);
  };

  return (
    <>
      {/* ── Chat Modal Panel (Desktop & Mobile) ── */}
      <AnimatePresence>
        {isAiChatOpen && (
          <motion.div
            initial={{ opacity: 0, y: 20, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 20, scale: 0.95 }}
            transition={{ duration: 0.25, ease: 'easeOut' }}
            className="fixed bottom-20 sm:bottom-24 right-4 sm:right-6 w-[calc(100vw-2rem)] sm:w-[440px] max-h-[620px] h-[82vh] rounded-[32px] bg-gradient-to-b from-[#180A26] via-[#140822] to-[#0D0417] border border-white/20 shadow-2xl z-50 flex flex-col justify-between overflow-hidden text-white backdrop-blur-2xl select-none"
          >
            {/* Panel Header */}
            <div className="p-4 sm:p-5 bg-white/[0.04] border-b border-white/10 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-[#6E2D8B] via-[#8E3EAF] to-[#FB7185] flex items-center justify-center text-white shadow-md shadow-purple-950/40">
                  <Bot className="w-5 h-5" />
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <h3 className="text-sm font-bold font-display text-white">OvaSense AI Twin</h3>
                    <span className="text-[9px] font-mono px-2 py-0.5 rounded-full bg-[#34D399]/20 text-[#34D399] font-bold">
                      Online
                    </span>
                  </div>
                  <span className="text-[11px] text-[#A797BD] font-sans">
                    Conversational health & ML insights companion
                  </span>
                </div>
              </div>

              <button
                type="button"
                onClick={closeAiChat}
                className="p-1.5 rounded-xl bg-white/10 hover:bg-white/20 text-[#CDBDD8] hover:text-white transition-colors cursor-pointer"
                aria-label="Close AI Chat"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Messages Scroll Area */}
            <div className="flex-1 p-4 overflow-y-auto space-y-3.5 text-left text-xs font-sans">
              {messages.map((m) => (
                <div
                  key={m.id}
                  className={`flex flex-col ${
                    m.sender === 'user' ? 'items-end' : 'items-start'
                  }`}
                >
                  <div className="flex items-start gap-2 max-w-[90%]">
                    {m.sender === 'ai' && (
                      <div className="w-6 h-6 rounded-lg bg-[#8E3EAF]/30 border border-[#8E3EAF]/40 flex items-center justify-center text-[#D8B4FE] shrink-0 mt-0.5">
                        <Sparkles className="w-3.5 h-3.5 text-[#FB7185]" />
                      </div>
                    )}
                    <div
                      className={`p-3.5 rounded-2xl leading-relaxed whitespace-pre-line ${
                        m.sender === 'user'
                          ? 'bg-gradient-to-r from-[#6E2D8B] to-[#8E3EAF] text-white rounded-br-xs shadow-md'
                          : 'bg-white/10 text-[#EDE4F7] border border-white/10 rounded-bl-xs'
                      }`}
                    >
                      {m.text}
                    </div>
                  </div>
                  <span className="text-[9px] font-mono text-[#8D7E9E] mt-1 px-1">
                    {m.timestamp}
                  </span>
                </div>
              ))}

              {isTyping && (
                <div className="flex items-center gap-1.5 p-3 rounded-2xl bg-white/5 border border-white/10 w-20 text-[#D8B4FE]">
                  <div className="w-2 h-2 rounded-full bg-[#FB7185] animate-bounce" />
                  <div className="w-2 h-2 rounded-full bg-[#8E3EAF] animate-bounce delay-150" />
                  <div className="w-2 h-2 rounded-full bg-[#D8B4FE] animate-bounce delay-300" />
                </div>
              )}
              <div ref={messagesEndRef} />
            </div>

            {/* Quick Prompt Chips */}
            <div className="p-3 bg-white/[0.02] border-t border-white/5 flex gap-1.5 overflow-x-auto no-scrollbar">
              {QUICK_PROMPTS.map((prompt, idx) => (
                <button
                  key={idx}
                  type="button"
                  onClick={() => handleSendMessage(prompt)}
                  className="px-2.5 py-1 rounded-full bg-white/10 hover:bg-[#8E3EAF]/40 text-[10px] font-medium text-[#EDE4F7] whitespace-nowrap transition-colors cursor-pointer border border-white/10"
                >
                  {prompt}
                </button>
              ))}
            </div>

            {/* Message Input Box */}
            <div className="p-3 sm:p-4 bg-white/[0.04] border-t border-white/10 space-y-2">
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  handleSendMessage();
                }}
                className="flex items-center gap-2"
              >
                <input
                  type="text"
                  placeholder="Ask about your PCOS screening, cycle, symptoms, or doctor prep..."
                  value={inputText}
                  onChange={(e) => setInputText(e.target.value)}
                  className="flex-1 px-4 py-2.5 rounded-2xl bg-[#12071F] border border-white/15 text-xs text-white placeholder-white/40 focus:outline-none focus:ring-1 focus:ring-[#8E3EAF]"
                />
                <button
                  type="submit"
                  disabled={!inputText.trim()}
                  className="p-2.5 rounded-2xl bg-gradient-to-r from-[#8E3EAF] to-[#E87084] text-white hover:brightness-110 shadow-md disabled:opacity-40 transition-all cursor-pointer"
                  aria-label="Send Message"
                >
                  <Send className="w-4 h-4" />
                </button>
              </form>

              <p className="text-[9px] text-[#8D7E9E] font-sans text-center">
                OvaSense AI provides educational explanations and is not a medical diagnostic device.
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* ── Floating Trigger Button (Available Globally) ── */}
      <div className="fixed bottom-20 md:bottom-8 right-5 sm:right-8 z-40 select-none">
        <motion.button
          type="button"
          onClick={toggleAiChat}
          whileHover={{ scale: 1.08 }}
          whileTap={{ scale: 0.94 }}
          className="relative group p-3.5 sm:p-4 rounded-full bg-gradient-to-tr from-[#6E2D8B] via-[#8E3EAF] to-[#FB7185] text-white shadow-2xl shadow-purple-950/70 border-2 border-white/40 flex items-center justify-center cursor-pointer transition-transform"
          aria-label="Ask OvaSense AI Twin"
        >
          {/* Subtle pulse wave ring */}
          <span className="absolute inset-0 rounded-full bg-[#FB7185]/30 animate-ping pointer-events-none" />

          <Sparkles className="w-6 h-6 text-white" />

          {/* Hover Tooltip (Desktop) */}
          <span className="hidden sm:group-hover:block absolute right-full mr-3 px-3 py-1.5 rounded-xl bg-[#180A26] text-white text-xs font-mono font-bold whitespace-nowrap shadow-xl border border-white/20">
            Ask OvaSense AI Twin ✨
          </span>
        </motion.button>
      </div>
    </>
  );
};
