/**
 * BioPulse AI — Unified Clinical Dashboard Iconography
 * 
 * Strict Single Icon Family: @untitledui/icons
 * Optical rules:
 * - Line styling: 1.5px–1.75px stroke visual weight (Untitled UI native)
 * - Navigation: 20x20px
 * - Buttons / Inputs: 18x18px
 * - Headings / Cards: 20x20px
 * - Metadata / Badges: 14–16px
 * - AI Companion: Mature conversation iconography (MessageChatCircle), no gimmicks (Sparkles/Bot)
 */

import {
  // Navigation & Core Domains
  LayoutGrid01,
  ClipboardCheck,
  Beaker01,
  LineChartUp01,
  Scales01,
  Activity,
  ActivityHeart,
  MessageChatCircle,
  File06,
  CalendarCheck01,
  MedicalCross,
  Calendar,
  Settings01,
  User01,
  Users01,
  Shield01,
  LogOut01,

  // Action & Utility Icons
  ArrowRight,
  ArrowLeft,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  Plus,
  XClose,
  Edit01,
  Trash01,
  Download01,
  UploadCloud01,
  SearchMd,
  FilterFunnel01,
  RefreshCw01,
  Check,
  CheckCircle,
  AlertCircle,
  AlertTriangle,
  InfoCircle,
  HelpCircle,
  Eye,
  EyeOff,
  Lock01,
  Clock,
  Loading01,
  BarChart01,
  LayersThree01,
  Send01,
  MedicalCircle,
} from '@untitledui/icons';

export const dashboardIcons = {
  // ── Navigation & Health Modules ──
  overview: LayoutGrid01,
  screening: ClipboardCheck,
  labs: Beaker01,
  progress: LineChartUp01,
  nutrition: Scales01,
  fitness: Activity,
  symptoms: ActivityHeart,
  aiCompanion: MessageChatCircle,
  reports: File06,
  appointments: CalendarCheck01,
  medications: MedicalCross,
  cycle: Calendar,
  careCircle: Users01,
  settings: Settings01,
  profile: User01,
  shield: Shield01,
  logout: LogOut01,

  // ── Actions & Indicators ──
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  plus: Plus,
  close: XClose,
  edit: Edit01,
  trash: Trash01,
  download: Download01,
  upload: UploadCloud01,
  search: SearchMd,
  filter: FilterFunnel01,
  refresh: RefreshCw01,
  check: Check,
  checkCircle: CheckCircle,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  info: InfoCircle,
  help: HelpCircle,
  eye: Eye,
  eyeOff: EyeOff,
  lock: Lock01,
  clock: Clock,
  spinner: Loading01,
  barChart: BarChart01,
  layers: LayersThree01,
  send: Send01,
  medicalCircle: MedicalCircle,
} as const;

export type DashboardIconKey = keyof typeof dashboardIcons;

// Direct re-exports for tree-shakeable direct component usage
export {
  LayoutGrid01,
  ClipboardCheck,
  Beaker01,
  LineChartUp01,
  Scales01,
  Activity,
  ActivityHeart,
  MessageChatCircle,
  File06,
  CalendarCheck01,
  MedicalCross,
  Calendar,
  Settings01,
  User01,
  Users01,
  Shield01,
  LogOut01,
  ArrowRight,
  ArrowLeft,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  Plus,
  XClose,
  Edit01,
  Trash01,
  Download01,
  UploadCloud01,
  SearchMd,
  FilterFunnel01,
  RefreshCw01,
  Check,
  CheckCircle,
  AlertCircle,
  AlertTriangle,
  InfoCircle,
  HelpCircle,
  Eye,
  EyeOff,
  Lock01,
  Clock,
  Loading01,
  BarChart01,
  LayersThree01,
  Send01,
  MedicalCircle,
};
