export const ROUTES = {
  // Public Marketing Routes
  HOME: '/',
  ABOUT: '/about',
  UNDERSTAND_PCOS: '/understand-pcos',
  UNDERSTAND_PCOS_CANONICAL: '/understand/pcos',
  UNDERSTAND_MALE_HYPOGONADISM: '/understand/male-hypogonadism',
  UNDERSTAND_HYPOGONADISM: '/understand-hypogonadism',
  UNDERSTAND_MALE_FERTILITY: '/understand/male-fertility',
  WOMENS_HEALTH: '/health/womens-health',
  MENS_HEALTH: '/health/mens-health',
  HOW_IT_WORKS: '/how-it-works',
  AI_EXPLAINS: '/ai-that-explains',
  FOR_DOCTORS: '/for-doctors',
  TRUST_PRIVACY: '/trust-and-privacy',
  FEATURES: '/features',
  CARE_CIRCLE: '/care-circle',
  CARE_PROVIDER_PORTAL: '/care-provider/:token',
  CONTACT: '/contact',

  // Authentication & Onboarding Routes
  LOGIN: '/login',
  REGISTER: '/register',
  ONBOARDING: '/onboarding',

  // Authenticated App Routes
  APP: {
    ROOT: '/app',
    DASHBOARD: '/app/dashboard',
    HUB: '/app/hub',
    AI_TWIN: '/app/ai-twin',
    CHAT: '/app/chat',
    PROFILE: '/app/profile',
    CYCLE: '/app/cycle',
    SYMPTOMS: '/app/symptoms',
    DIET: '/app/diet',
    DIET_WEEK: '/app/diet/week',
    FITNESS: '/app/fitness',
    REPORTS: '/app/reports',
    MEDICATIONS: '/app/medications',
    CARE_CIRCLE: '/app/care-circle',
    APPOINTMENTS: '/app/appointments',
    ASSESSMENT: '/app/assessment',
    LIFESTYLE: '/app/lifestyle',
    TIMELINE: '/app/timeline',
    SETTINGS: '/app/settings',
  },
} as const;
